function Fig = plot2dspectrum(XData, CData_A, CData_B, pval, CMap, YLim, idx_ev, idx_ss, highlight)

Fig = figure('Position', [420 420 650 420]);
    
Ax(1) = axes(...
    'Box', 'on', ...
    'NextPlot', 'add', ...
    'Color', [233, 236, 239]./255, ...
    'XLim', [min(XData), max(XData)], ...
    'YLim', YLim, ...
    'XTick', [4, 8, 12, 16], ...
    'XColor', [0.5, 0.5, 0.5], ...
    'YColor', [0.5, 0.5, 0.5], ...
    'XTickLabel', {}, ...
    'XGrid', 'on', ...
    'YGrid', 'off', ...
    'YMinorGrid', 'off', ...
    'GridAlpha', 0.25, ...
    'LineWidth', 0.5, ...
    'TickLength', [0, 0], ...
    'FontSize', 10, ...
    'Layer', 'top', ...
    'Units', 'normalized', ...
    'Position', [0.13 0.35 0.57 0.65], ...
    'Toolbar', [], ...
    'Interactions', []);

ylabel('Power (\muV^2/Hz)', 'FontSize', 10)

for i = 1:size(CData_A, 1)
    patch(Ax(1), 'XData', [asrow(XData), nan], 'YData', [asrow(squeeze(CData_A(i, :))), nan], ...
        'EdgeColor', CMap(1, :), ...
        'EdgeAlpha', 0.05)
end
for i = 1:size(CData_B, 1)
    patch(Ax(1), 'XData', [asrow(XData), nan], 'YData', [asrow(squeeze(CData_B(i, :))), nan], ...
        'EdgeColor', CMap(end, :), ...
        'EdgeAlpha', 0.05)
end

clear h

h(1) = patch(Ax(1), 'XData', [asrow(XData), nan], 'YData', [asrow(squeeze(mean(CData_A, 1, 'omitnan'))), nan], ...
    'LineWidth', 2, ...
    'FaceColor', CMap(1, :), ...
    'EdgeColor', CMap(1, :), ...
    'FaceAlpha', 1, ...
    'EdgeAlpha', 1);

h(2) = patch(Ax(1), 'XData', [asrow(XData), nan], 'YData', [asrow(squeeze(mean(CData_B, 1, 'omitnan'))), nan], ...
    'LineWidth', 2, ...
    'FaceColor', CMap(end, :), ...
    'EdgeColor', CMap(end, :), ...
    'FaceAlpha', 1, ...
    'EdgeAlpha', 1);

leg = legend(h(1:2), {sprintf('Continued sleep (N = %i)', sum(idx_ev & ~idx_ss)), sprintf('State-shift (N = %i)', sum(idx_ev & idx_ss))}, 'Box', 'off', 'FontSize', 10);

Ax(2) = axes(...
    'Box', 'on', ...
    'NextPlot', 'add', ...
    'Color', [233, 236, 239]./255, ...
    'XLim', [min(XData), max(XData)], ...
    'YLim', [0, 100], ...
    'XTick', [4, 8, 12, 16], ...
    'YTick', [0, 100], ...
    'XColor', [0.5, 0.5, 0.5], ...
    'YColor', [0.5, 0.5, 0.5], ...
    'XGrid', 'on', ...
    'YGrid', 'off', ...
    'YMinorGrid', 'off', ...
    'GridAlpha', 0.25, ...
    'LineWidth', 0.5, ...
    'TickLength', [0, 0], ...
    'FontSize', 10, ...
    'Layer', 'top', ...
    'Units', 'normalized', ...
    'Position', [0.13 0.13 0.57 0.16], ...
    'Toolbar', [], ...
    'Interactions', []);

xlabel('Frequency (Hz)', 'FontSize', 10)
ylabel('% chans', 'FontSize', 10)

clear h

h(1) = patch(Ax(2), 'XData', [0, asrow(XData), XData(end)], 'YData', [0, 100*sum(pval < 0.05)./size(pval, 1), 0], ...
    'FaceAlpha', 0.8, ...
    'LineStyle', 'none', ...
    'FaceColor', [0.49 0.5 0.51]);

h(2) = patch(Ax(2), 'XData', [0, asrow(XData), XData(end)], 'YData', [0, 100*sum(pval < 0.01)./size(pval, 1), 0], ...
    'FaceAlpha', 0.8, ...
    'LineStyle', 'none', ...
    'FaceColor', [0.29 0.3 0.31]);

h(3) = patch(Ax(2), 'XData', [0, asrow(XData), XData(end)], 'YData', [0, 100*sum(pval < 0.001)./size(pval, 1), 0], ...
    'FaceAlpha', 0.8, ...
    'LineStyle', 'none', ...
    'FaceColor', [0.09 0.1 0.11]);

for i = 1:size(highlight, 1)
    plot(Ax(2), [highlight(i, 1), highlight(i, 1), highlight(i, 2), highlight(i, 2)], [0, 95, 95, 0], ':k', 'LineWidth', 1)
    text(Ax(2), [highlight(i, 1), highlight(i, 2)], [100 100], {sprintf('%.1f', highlight(i, 1)), sprintf('%.1f', highlight(i, 2))}, 'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'center', 'FontSize', 10)
end

leg = legend(h, {'p < 0.05', 'p < 0.01', 'p < 0.001'}, 'Box', 'off', 'FontSize', 10, 'location', 'eastoutside');

Ax(2).Position(3) = 0.57;

end