function Ax = plotarousalersp(Fig, XData, YData, CData, Interval, CMap, CLim)
% -------------------------------------------------------------------------
% ERSP
i = 1;
Ax(i) = uiaxes(Fig, ...
    'Box', 'on', ...
    'NextPlot', 'add', ...
    'Color', [233, 236, 239]./255, ...
    'XColor', [0.5, 0.5, 0.5], ...
    'YColor', [0.5, 0.5, 0.5], ...
    'XGrid', 'on', ...
    'YGrid', 'on', ...
    'YMinorGrid', 'off', ...
    'GridAlpha', 0.25, ...
    'LineWidth', 1, ...
    'TickLength', [0, 0], ...
    'FontSize', 7, ...
    'Layer', 'bottom', ...
    'Units', 'normalized', ...
    'Toolbar', [], ...
    'Interactions', []);
Ax(i).Title.String = ' ';
Ax(i).Title.FontSize = 8;
Ax(i).Title.FontWeight = 'normal';
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
H = pcolor(Ax(i), XData, YData, CData);
H.LineStyle = 'none';
drawnow();
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ax(i).XLabel.String = ' ';
Ax(i).XLabel.FontSize = 8;
Ax(i).XLabel.Units = 'normalized';
Ax(i).YLabel.String = ' ';
Ax(i).YLabel.FontSize = 8;
Ax(i).YLabel.Units = 'normalized';
Ax(i).Layer = 'top';
Ax(i).XLim = Interval;
Ax(i).XTick = sort([0, Interval]);
Ax(i).XTickLabel = {};
Ax(i).CLim = CLim;
Ax(i).Colormap = CMap;
Ax(i).YLim = [min(YData), max(YData)];
Ax(i).YTick = [4 8 12 16 24];
Ax(i).YTickLabel = {};
Ax(i).GridColor = 'w';
Ax(i).GridAlpha = 0.367;
Ax(i).InnerPosition = [0.15 0.15 0.85 0.85]; 

% -------------------------------------------------------------------------
% Mean spectral power
i = 2;
Ax(i) = uiaxes(Fig, ...
    'Box', 'on', ...
    'NextPlot', 'add', ...
    'Color', [233, 236, 239]./255, ...
    'XColor', [0.5, 0.5, 0.5], ...
    'YColor', [0.5, 0.5, 0.5], ...
    'XGrid', 'on', ...
    'YGrid', 'on', ...
    'YMinorGrid', 'off', ...
    'GridAlpha', 0.25, ...
    'LineWidth', 0.5, ...
    'TickLength', [0, 0], ...
    'FontSize', 7, ...
    'Layer', 'bottom', ...
    'Units', 'normalized', ...
    'Toolbar', [], ...
    'Interactions', []);
Ax(i).Title.FontSize = 8;
Ax(i).Title.FontWeight = 'normal';
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
PData = mean(CData(:, XData <= -1), 2);
plot(Ax(i), PData, YData, '-k', 'LineWidth', 1)
Ax(i).InnerPosition = [0 0.15 0.15 0.85];
Ax(i).YLabel.String = 'freq. (Hz)';
Ax(i).YLabel.FontSize = 8;
Ax(i).YLabel.Units = 'normalized';
Ax(i).Layer = 'top';
Ax(i).XAxisLocation = 'top';
Ax(i).XTick = max(CLim);
Ax(i).XLim = CLim;
Ax(i).YLim = [min(YData), max(YData)];
Ax(i).YTick = [4 8 12 16 24];
Ax(i).GridColor = 'w';
Ax(i).GridAlpha = 0.367;

% -------------------------------------------------------------------------
% Total power
i = 3;
Ax(i) = uiaxes(Fig, ...
    'Box', 'on', ...
    'NextPlot', 'add', ...
    'Color', [233, 236, 239]./255, ...
    'XColor', [0.5, 0.5, 0.5], ...
    'YColor', [0.5, 0.5, 0.5], ...
    'XGrid', 'on', ...
    'YGrid', 'on', ...
    'YMinorGrid', 'off', ...
    'GridAlpha', 0.25, ...
    'LineWidth', 0.5, ...
    'TickLength', [0, 0], ...
    'FontSize', 7, ...
    'Layer', 'bottom', ...
    'Units', 'normalized', ...
    'Toolbar', [], ...
    'Interactions', []);
Ax(i).Title.FontSize = 8;
Ax(i).Title.FontWeight = 'normal';
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
PData = mean(CData, 1);
plot(Ax(i), XData, PData, '-k', 'LineWidth', 1)
Ax(i).InnerPosition = [0.15 0 0.85 0.15];
Ax(i).XLabel.String = 'time (s)';
Ax(i).XLabel.FontSize = 8;
Ax(i).XLabel.Units = 'normalized';
Ax(i).Layer = 'top';
Ax(i).XLim = Interval;
Ax(i).XTick = sort([0, Interval]);
Ax(i).YLim = CLim;
Ax(i).YTick = max(CLim);
Ax(i).YAxisLocation = 'right';
Ax(i).GridColor = 'w';
Ax(i).GridAlpha = 0.367;

end