function fsig = isffilterbout(sig, filtcfg)
fsig = sig;
fsig.data = detrend(fsig.data', 0)';
% Get prepend and append signals
fsig = signalappend(fsig, 'zeros', filtcfg.ford_mult, filtcfg);
% Append data
fsig = applyappend(fsig);
% Filter data within ISF freq range
fsig = pop_firws(fsig, ...
    'fcutoff', filtcfg.cutoff, ...
    'ftype', 'bandpass', ...
    'wtype', filtcfg.wintype, ...
    'warg', filtcfg.warg, ...
    'forder', filtcfg.order, ...
    'plotfresp', false, ...
    'minphase', 0);

end